name: sync-token-lists
run-name: Daily Sync Token Lists
on:
  schedule:
    # Run every 24 hours, 00:00 UTC
    - cron: '0 0 * * *'
jobs:
  daily-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions [Bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: Sync Token Lists
        run: |
          "node ./scripts/sync-token-lists.mjs"
      - name: Check Git Status and Commit
      # if any changes are made, we will commit and push them
        run: |
          git status
          git add .
          if git diff --exit-code --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync Token Lists at $(date)"
            git push
          fi